#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Unity Skills Python Helper
# Auto-generated by UnitySkills

# CRITICAL: Fix Windows console encoding BEFORE any other imports or print statements
# This must be at the very top of the module to work correctly
import sys
if sys.platform == 'win32':
    import codecs
    if hasattr(sys.stdout, 'buffer'):
        sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'replace')
    if hasattr(sys.stderr, 'buffer'):
        sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'replace')

import requests
import time
import json
import os
import re
import threading
from pathlib import Path
from typing import Any, Dict, List, Optional
from urllib.parse import urlencode

__version__ = "2.4.2"

UNITY_URL = "http://localhost:8090"
DEFAULT_PORT = 8090
PORT_RANGE_START = 8090
PORT_RANGE_END = 8100

# Timeout constants (seconds)
DEFAULT_CALL_TIMEOUT = 900
HEALTH_TIMEOUT = 2
SCAN_TIMEOUT = 1

# Registry entries whose last_active heartbeat is older than this are treated as
# dead. Matches the server's own stale-reaping threshold (RegistryService, 120s;
# heartbeat interval is ~30s).
REGISTRY_STALE_SECONDS = 120


def _normalize_project_path(path: str) -> Optional[str]:
    """Return a canonical path suitable for comparing project directories."""
    if not path:
        return None

    try:
        return os.path.normcase(
            os.path.realpath(os.path.abspath(os.path.expanduser(os.fspath(path))))
        )
    except (OSError, TypeError, ValueError):
        return None


def _project_path_match_score(current_directory: str, project_path: str) -> int:
    """Return a positive score when the current directory belongs to a project.

    A project root also matches its subdirectories. The normalized path length is
    used as the score so the most specific project wins when projects are nested.
    """
    normalized_current = _normalize_project_path(current_directory)
    normalized_project = _normalize_project_path(project_path)
    if not normalized_current or not normalized_project:
        return 0

    try:
        if os.path.commonpath([normalized_current, normalized_project]) != normalized_project:
            return 0
    except ValueError:
        # commonpath raises for paths on different drives on Windows.
        return 0

    return len(normalized_project)


def get_registry_path():
    return os.path.join(os.path.expanduser("~"), ".unity_skills", "registry.json")


def _load_registry():
    reg_path = get_registry_path()
    if not os.path.exists(reg_path):
        return {}
    try:
        with open(reg_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except IOError:
        return {}
    except json.JSONDecodeError as exc:
        print(f"[unity-skills] registry.json is invalid JSON: {exc}", file=sys.stderr)
        return {}


def _get_agent_id():
    try:
        config_path = os.path.join(os.path.dirname(__file__), 'agent_config.json')
        if os.path.exists(config_path):
            with open(config_path, 'r', encoding='utf-8') as f:
                return json.load(f).get('agentId', 'Python')
    except (IOError, json.JSONDecodeError):
        pass
    return 'Python'


def _version_matches(actual_version: str, target: str) -> bool:
    """
    Version prefix matching with Unity 6 special format support.

    Unity 6 uses internal version like '6000.0.xxf1', so user input '6' or 'Unity 6'
    should match '6000.x.x'. Traditional versions like '2022.3.12f1' use direct prefix matching.

    Examples:
        _version_matches("6000.0.28f1", "6")       -> True
        _version_matches("6000.0.28f1", "Unity 6")  -> True
        _version_matches("6000.0.28f1", "6000")     -> True
        _version_matches("2022.3.12f1", "2022")     -> True
        _version_matches("2022.3.12f1", "2022.3")   -> True
        _version_matches("2022.3.12f1", "6")        -> False
    """
    if not actual_version or not target:
        return False

    cleaned = target.strip()
    if cleaned.lower().startswith("unity"):
        cleaned = cleaned[5:].strip()

    if not cleaned:
        return False

    # Unity 6 special mapping: user says "6", "6.1", "6.2" etc -> match "6000."
    if cleaned.split(".")[0] == "6" and not cleaned.startswith("6000"):
        return actual_version.startswith("6000.")

    # Direct prefix match for everything else (e.g. "6000", "2022", "2022.3")
    return actual_version.startswith(cleaned)


def _is_retryable_transport_error(result: Dict[str, Any]) -> bool:
    if not isinstance(result, dict) or result.get('success'):
        return False

    transport_error = result.get('transportError')
    if transport_error in {'connection', 'timeout'}:
        return True

    error_text = str(result.get('error', '')).lower()
    return (
        'cannot connect' in error_text
        or 'timed out' in error_text
        or 'read timed out' in error_text
        or 'connection aborted' in error_text
    )


# Server-side "wait and retry" contract (see SkillErrorResponse.Build in SkillsHttpServer.cs):
# COMPILING / RATE_LIMIT / QUEUE_FULL / SERVER_STOPPED are all transient-unavailability
# responses carrying retryStrategy == "wait_and_retry" plus a retryAfterSeconds hint, sent
# as HTTP 503 (COMPILING, QUEUE_FULL, SERVER_STOPPED) or 429 (RATE_LIMIT) with a valid JSON
# body — not a connection/timeout exception, so _is_retryable_transport_error() above never
# sees them.
_RETRYABLE_ERROR_CODES = {'COMPILING', 'RATE_LIMIT', 'QUEUE_FULL', 'SERVER_STOPPED'}
_RETRYABLE_HTTP_STATUS = {429, 503}
_DEFAULT_STRUCTURED_RETRY_SECONDS = 2.0
_MAX_STRUCTURED_RETRY_SECONDS = 15.0


def _structured_retry_after(data: Dict[str, Any], status_code: Optional[int] = None) -> Optional[float]:
    """Return the wait time (seconds) before retrying a structured server error response,
    or None when the error is not one of the server's transient-unavailability responses.

    HTTP 503/429 without a matching errorCode/retryStrategy is still treated as retryable
    as an auxiliary signal, so a future transient code added under the same status lines
    is retried without a client update.
    """
    if not isinstance(data, dict):
        return None

    is_retryable = (
        data.get('errorCode') in _RETRYABLE_ERROR_CODES
        or data.get('retryStrategy') == 'wait_and_retry'
        or status_code in _RETRYABLE_HTTP_STATUS
    )
    if not is_retryable:
        return None

    retry_after = data.get('retryAfterSeconds')
    if not isinstance(retry_after, (int, float)) or retry_after <= 0:
        retry_after = _DEFAULT_STRUCTURED_RETRY_SECONDS
    return min(float(retry_after), _MAX_STRUCTURED_RETRY_SECONDS)


class UnitySkills:
    """
    Client for interacting with a specific Unity Editor instance.
    """
    def __init__(self, port: int = None, target: str = None, url: str = None, version: str = None, agent_id: str = None, timeout: int = None):
        """
        Initialize client.
        Args:
            port: Connect to specific localhost port (e.g. 8091)
            target: Connect to instance by Name or ID (e.g. "MyGame" or "MyGame_A1B2") - auto-discovers port.
            url: Full URL override.
            version: Connect to instance by Unity version (e.g. "6", "2022", "2022.3") - auto-discovers port.
            agent_id: Custom agent identifier (e.g. "MyScript", "ClaudeCode")
            timeout: Request timeout in seconds (default: 900)
        Priority: url > port > target > version > auto-discovery
        """
        self.url = url
        self.agent_id = agent_id or _get_agent_id()
        self.timeout = timeout or DEFAULT_CALL_TIMEOUT
        # Reuse a Session so TCP connections stay warm across requests.
        self._session = requests.Session()
        self._session.headers.update({
            'X-Agent-Id': self.agent_id,
            'User-Agent': f'unity-skills-python/{__version__}',
        })
        # /health payload captured during port discovery (or first lazy fetch);
        # shared by timeout sync and disk-cache keying so construction issues at
        # most one /health request.
        self._health_info = None

        if not self.url:
            if port:
                self.url = f"http://localhost:{port}"
            elif target:
                found_port = self._find_port_by_target(target)
                if found_port:
                    self.url = f"http://localhost:{found_port}"
                else:
                    raise ValueError(f"Could not find Unity instance matching '{target}' in registry.")
            elif version:
                found_port = self._find_port_by_version(version)
                if found_port:
                    self.url = f"http://localhost:{found_port}"
                else:
                    raise ValueError(f"Could not find Unity instance matching version '{version}'.")
            else:
                # Auto-discover: prefer the current project's registry entry, then other
                # registry ports, and finally scan 8090-8100.
                found_port = self._find_first_available()
                self.url = f"http://localhost:{found_port}"

        if not timeout:
            self._sync_timeout_from_server()

    def _fetch_health(self, base_url: str, timeout: float = HEALTH_TIMEOUT) -> Optional[Dict[str, Any]]:
        """GET {base_url}/health and return the parsed JSON dict, or None if unreachable."""
        try:
            resp = self._session.get(f"{base_url}/health", timeout=timeout)
            if resp.status_code == 200:
                data = resp.json()
                if isinstance(data, dict):
                    return data
        except (requests.exceptions.RequestException, ValueError):
            pass
        return None

    def _get_health_info(self) -> Optional[Dict[str, Any]]:
        """Return this instance's /health payload, fetching once and caching it."""
        if self._health_info is None:
            self._health_info = self._fetch_health(self.url)
        return self._health_info

    def _sync_timeout_from_server(self):
        """Apply requestTimeoutMinutes from /health as self.timeout.

        Reuses the health payload captured during port discovery when available,
        so no extra request is issued on the auto-discover path.
        """
        health = self._get_health_info()
        if health:
            minutes = health.get('requestTimeoutMinutes')
            if minutes and isinstance(minutes, (int, float)) and minutes > 0:
                self.timeout = int(minutes) * 60

    def _registry_candidate_ports(self) -> List[int]:
        """Return live registry ports in their preferred probing order.

        Entries whose last_active heartbeat (unix seconds, refreshed every ~30s by
        the server) is older than REGISTRY_STALE_SECONDS are skipped, as are
        malformed entries. Entries matching the current working directory are
        preferred; within each group, the freshest heartbeat wins. The caller's
        port scan remains the safety net.
        """
        candidates = []
        now = time.time()
        current_directory = os.getcwd()
        for registry_path, info in _load_registry().items():
            if not isinstance(info, dict):
                continue
            port = info.get('port')
            last_active = info.get('last_active')
            if not isinstance(port, int) or port <= 0:
                continue
            if not isinstance(last_active, (int, float)) or (now - last_active) > REGISTRY_STALE_SECONDS:
                continue

            project_path = info.get('path') or registry_path
            path_match_score = _project_path_match_score(current_directory, project_path)
            candidates.append((path_match_score, last_active, port))

        candidates.sort(reverse=True)
        return list(dict.fromkeys(port for _, _, port in candidates))

    def _find_first_available(self) -> int:
        """Find the first responsive Unity instance.

        Tries the current project's live registry entry first, followed by other
        live entries ordered by heartbeat. Falls back to scanning ports 8090-8100
        when the registry is missing, stale, or its entries stop responding. The
        winning /health payload is kept on self._health_info so it is not fetched
        a second time.
        """
        tried = set()
        for port in self._registry_candidate_ports():
            tried.add(port)
            health = self._fetch_health(f"http://localhost:{port}", timeout=HEALTH_TIMEOUT)
            if health is not None:
                self._health_info = health
                return port
        for port in range(PORT_RANGE_START, PORT_RANGE_END + 1):
            if port in tried:
                continue
            health = self._fetch_health(f"http://localhost:{port}", timeout=SCAN_TIMEOUT)
            if health is not None:
                self._health_info = health
                return port
        raise ConnectionError(f"No Unity instance found on ports {PORT_RANGE_START}-{PORT_RANGE_END}. Is UnitySkills server running?")

    def _find_port_by_target(self, target: str) -> Optional[int]:
        data = _load_registry()
        for path, info in data.items():
            if info.get('id') == target:
                return info.get('port')
        for path, info in data.items():
            if info.get('name') == target:
                return info.get('port')
        return None

    def _find_port_by_version(self, version: str) -> Optional[int]:
        """
        Find a Unity instance port by version string.

        Three-stage search strategy (decreasing efficiency):
        1. Check registry - read unityVersion field from registry.json (no HTTP overhead)
        2. Probe health - when registry has no version info (old server), call /health on registered ports
        3. Scan ports - when registry is empty/missing, scan ports 8090-8100
        """
        registry_data = _load_registry() or None

        # Stage 1: Check registry unityVersion field
        if registry_data:
            for path, info in registry_data.items():
                reg_version = info.get('unityVersion')
                if reg_version and _version_matches(reg_version, version):
                    port = info.get('port')
                    if port:
                        return port

            # Stage 2: Probe /health for registered ports without version info
            ports_without_version = []
            for path, info in registry_data.items():
                if not info.get('unityVersion') and info.get('port'):
                    ports_without_version.append(info['port'])

            for port in ports_without_version:
                try:
                    resp = requests.get(f"http://localhost:{port}/health", timeout=HEALTH_TIMEOUT)
                    if resp.status_code == 200:
                        health_data = resp.json()
                        health_version = health_data.get('unityVersion')
                        if health_version and _version_matches(health_version, version):
                            return port
                except (requests.exceptions.RequestException, ValueError):
                    continue

        # Stage 3: Scan port range (fallback when registry is empty/missing)
        if not registry_data:
            for port in range(PORT_RANGE_START, PORT_RANGE_END + 1):
                try:
                    resp = requests.get(f"http://localhost:{port}/health", timeout=SCAN_TIMEOUT)
                    if resp.status_code == 200:
                        health_data = resp.json()
                        health_version = health_data.get('unityVersion')
                        if health_version and _version_matches(health_version, version):
                            return port
                except (requests.exceptions.RequestException, ValueError):
                    continue

        return None

    def _post_skill(self, skill_name: str, payload: Dict[str, Any], mode: str = None, timeout: Optional[int] = None):
        params = {}
        if mode:
            params['mode'] = mode
        qs = f"?{urlencode(params)}" if params else ""
        json_data = json.dumps(payload, ensure_ascii=False)
        response = self._session.post(
            f"{self.url}/skill/{skill_name}{qs}",
            data=json_data.encode('utf-8'),
            headers={'Content-Type': 'application/json; charset=utf-8'},
            timeout=timeout or self.timeout
        )
        response.encoding = 'utf-8'
        return response

    def _timeout_error_result(self, timeout: Optional[float] = None) -> Dict[str, Any]:
        effective_timeout = timeout if timeout is not None else self.timeout
        return {
            'success': False,
            'error': f"Request to {self.url} timed out after {effective_timeout} seconds.",
            'transportError': 'timeout',
            'retryable': True,
            'suggestion': 'Unity may still be compiling scripts or processing a long-running operation. Wait a moment and retry.',
        }

    def _connection_error_result(self) -> Dict[str, Any]:
        return {
            'success': False,
            'error': f"Cannot connect to {self.url}. Unity instance may be down.",
            'transportError': 'connection',
            'retryable': True,
            'suggestion': 'Unity may be recompiling scripts (Domain Reload). Wait 3-5 seconds and retry.',
            'hint': 'Check if server is running: open Window > UnitySkills and toggle the server switch'
        }

    def _post_skill_with_retries(self, skill_name: str, payload: Dict[str, Any], mode: str = None,
                                  timeout: Optional[int] = None, _retries: int = 3,
                                  _retry_delay: float = 2.0) -> Dict[str, Any]:
        """Shared retry loop for POST /skill/{name}, used by call(), dry_run_skill() and plan_skill().

        Retries (within the shared `_retries` budget) on two kinds of transient failure:
          - transport errors (connection refused / timed out) -- typical while Unity is
            mid Domain Reload and the HTTP listener itself is down;
          - structured "wait and retry" error bodies the server returns once the listener
            IS up but a skill can't run yet (COMPILING/RATE_LIMIT/QUEUE_FULL/SERVER_STOPPED;
            see _structured_retry_after()). The wait uses the server's own retryAfterSeconds
            when present.

        Retries exhausted on a structured error still return {'ok': True, ...} with the
        server's last response/data untouched, so callers see the real error payload
        rather than a synthesized one.

        Returns one of:
          {'ok': True, 'response': <requests.Response>, 'data': <parsed JSON dict>}
          {'ok': False, 'transport_error': <dict from _timeout_error_result/_connection_error_result>}
          {'ok': False, 'invalid_json': <response.text>}
          {'ok': False, 'exception': <str(exc)>}   # any other exception, not retried
        """
        for attempt in range(_retries + 1):
            try:
                response = self._post_skill(skill_name, payload, mode=mode, timeout=timeout)
            except requests.exceptions.Timeout:
                if attempt < _retries:
                    time.sleep(_retry_delay * (attempt + 1))
                    continue
                return {'ok': False, 'transport_error': self._timeout_error_result(timeout)}
            except requests.exceptions.ConnectionError:
                if attempt < _retries:
                    time.sleep(_retry_delay * (attempt + 1))
                    continue
                return {'ok': False, 'transport_error': self._connection_error_result()}
            except Exception as e:
                return {'ok': False, 'exception': str(e)}

            try:
                data = response.json()
            except ValueError:
                return {'ok': False, 'invalid_json': response.text}

            if isinstance(data, dict) and data.get('status') == 'error':
                retry_after = _structured_retry_after(data, response.status_code)
                if retry_after is not None and attempt < _retries:
                    time.sleep(retry_after)
                    continue

            return {'ok': True, 'response': response, 'data': data}

        # Unreachable: every branch above either continues or returns.
        return {'ok': False, 'exception': 'retry loop exhausted unexpectedly'}

    @staticmethod
    def _mode_result_from_outcome(outcome: Dict[str, Any]) -> Dict[str, Any]:
        """Shape a _post_skill_with_retries() outcome into dry_run_skill/plan_skill's
        historical {'status': ..., ...} return format (the server's raw JSON on success,
        unlike call()'s normalized {'success': ...} shape)."""
        if outcome['ok']:
            return outcome['data']
        if 'invalid_json' in outcome:
            return {'status': 'error', 'error': f"Invalid JSON response: {outcome['invalid_json']}"}
        if 'transport_error' in outcome:
            return {'status': 'error', 'error': outcome['transport_error'].get('error', 'Transport error')}
        return {'status': 'error', 'error': outcome.get('exception', 'Unknown error')}

    def call(self, skill_name: str, verbose: bool = False, wait_for_job: bool = False,
             job_timeout: float = 60.0, _retries: int = 3, _retry_delay: float = 2.0,
             timeout: Optional[int] = None, **kwargs) -> Dict[str, Any]:
        """
        Call a skill on this instance with automatic retry on connection errors and on the
        server's structured "wait and retry" responses (COMPILING/RATE_LIMIT/QUEUE_FULL/
        SERVER_STOPPED -- see SkillErrorResponse.Build in SkillsHttpServer.cs).

        Args:
            skill_name: Name of the skill to call
            verbose: Whether to return verbose output
            _retries: Number of retries on connection error or transient server error (default 3)
            _retry_delay: Base delay between transport-error retries in seconds (default 2.0),
                uses progressive backoff. Retries triggered by a structured server error use
                the server's own retryAfterSeconds instead (capped at 15s).
            timeout: Per-call request timeout override in seconds. None (default) reuses the
                instance-level timeout set at construction.

        Returns a normalized response with 'success' field and flattened result data.
        Error responses additionally carry the server's structured correction fields
        (errorCode, details, suggestedFixes, retryStrategy, ...) when the server sent them.
        """
        kwargs['verbose'] = verbose
        outcome = self._post_skill_with_retries(
            skill_name, kwargs, timeout=timeout, _retries=_retries, _retry_delay=_retry_delay)

        if not outcome['ok']:
            if 'invalid_json' in outcome:
                return {'success': False, 'error': f"Invalid JSON response: {outcome['invalid_json']}"}
            if 'transport_error' in outcome:
                return outcome['transport_error']
            return {'success': False, 'error': outcome.get('exception', 'Unknown error')}

        data = outcome['data']
        if data.get('status') == 'success':
            result = data.get('result', {})
            normalized = {'success': True}
            if isinstance(result, dict):
                normalized.update(result)
            else:
                normalized['result'] = result
            if wait_for_job and isinstance(normalized, dict) and normalized.get('jobId'):
                return self.wait_for_job(normalized['jobId'], timeout=job_timeout)
            return normalized
        elif data.get('status') == 'error':
            normalized = {
                'success': False,
                'error': data.get('error', 'Unknown error'),
            }
            # Preserve the server's structured correction fields (did-you-mean
            # suggestions, allowedParams, retry guidance) when present, so
            # agents can self-correct without a human round-trip.
            for key in ('errorCode', 'details', 'suggestedFixes', 'retryStrategy',
                        'relatedSkills', 'retryAfterSeconds', 'skill', 'message'):
                if key in data:
                    normalized[key] = data[key]
            return normalized
        else:
            if wait_for_job and isinstance(data, dict) and data.get('jobId'):
                return self.wait_for_job(data['jobId'], timeout=job_timeout)
            return data

    def dry_run_skill(self, skill_name: str, timeout: Optional[int] = None,
                      _retries: int = 3, _retry_delay: float = 2.0, **kwargs) -> Dict[str, Any]:
        """Validate a Unity skill call without executing it.

        Shares call()'s retry logic (see _post_skill_with_retries): retries transport
        errors and the server's structured "wait and retry" responses up to `_retries`
        times before returning.
        """
        outcome = self._post_skill_with_retries(
            skill_name, kwargs, mode='dryRun', timeout=timeout,
            _retries=_retries, _retry_delay=_retry_delay)
        return self._mode_result_from_outcome(outcome)

    def plan_skill(self, skill_name: str, timeout: Optional[int] = None,
                   _retries: int = 3, _retry_delay: float = 2.0, **kwargs) -> Dict[str, Any]:
        """Preview a Unity skill call with generic/semantic planning details.

        Shares call()'s retry logic; see dry_run_skill().
        """
        outcome = self._post_skill_with_retries(
            skill_name, kwargs, mode='plan', timeout=timeout,
            _retries=_retries, _retry_delay=_retry_delay)
        return self._mode_result_from_outcome(outcome)

    def plan_workflow(self, skills: List[Dict[str, Any]]) -> Dict[str, Any]:
        return self.call('workflow_plan', skillsJson=json.dumps(skills, ensure_ascii=False))

    def get_job_status(self, job_id: str) -> Dict[str, Any]:
        return self.call('job_status', jobId=job_id)

    def get_job_logs(self, job_id: str, limit: int = 100) -> Dict[str, Any]:
        return self.call('job_logs', jobId=job_id, limit=limit)

    def wait_for_job(self, job_id: str, timeout: float = 60.0) -> Dict[str, Any]:
        """Wait for a job to finish, polling GET /jobs/{id} until terminal or `timeout`.

        Polls the lightweight /jobs/{id} snapshot instead of calling the blocking
        `job_wait` skill. `job_wait` runs a Thread.Sleep loop on the Unity main thread,
        which freezes the editor and blocks /health and every other request for the full
        timeout (up to 60s here). Polling issues only short, non-blocking reads, so the
        main thread stays free between polls and /health stays responsive.

        `timeout` (default 60s) is the total wait budget; poll interval starts at 0.5s
        and backs off to 5s for long-running jobs.

        Returns a shape compatible with the historical job_wait result (`success`,
        `status`, `reportId`, `report`, `error`, …). `success` is True only when the
        job reached `completed` (stricter than the old job_wait, which always returned
        success=True for any found job — a failed/cancelled job now reports success=False).
        """
        snapshot = self.poll_job(job_id, interval=0.5, timeout=timeout)
        if not isinstance(snapshot, dict):
            return snapshot or {'success': False, 'error': 'wait_for_job returned no snapshot'}

        status = snapshot.get('status')
        result = {
            'success': status == 'completed',
            'jobId': snapshot.get('jobId'),
            'status': status,
            'progress': snapshot.get('progress'),
            'currentStage': snapshot.get('currentStage'),
            'reportId': snapshot.get('reportId'),
            'workflowId': snapshot.get('relatedWorkflowId'),
            'resultSummary': snapshot.get('resultSummary'),
            'error': snapshot.get('error'),
            'details': snapshot.get('resultData'),
            'terminal': snapshot.get('terminal'),
        }
        if snapshot.get('_pollTimeout'):
            result['timedOut'] = True
        if result.get('reportId'):
            report = self.call('batch_report_get', reportId=result['reportId'])
            if isinstance(report, dict) and report.get('success'):
                result['report'] = report
        return result

    def get_job(self, job_id: str) -> Dict[str, Any]:
        """Read a job snapshot via GET /jobs/{id} (lightweight, bypasses skill router)."""
        try:
            resp = self._session.get(f"{self.url}/jobs/{job_id}", timeout=HEALTH_TIMEOUT)
            return resp.json()
        except Exception as exc:
            return {'status': 'error', 'error': str(exc)}

    def list_jobs(self, limit: int = 50) -> Dict[str, Any]:
        """List recent jobs via GET /jobs."""
        try:
            resp = self._session.get(f"{self.url}/jobs?limit={int(limit)}", timeout=HEALTH_TIMEOUT)
            return resp.json()
        except Exception as exc:
            return {'status': 'error', 'error': str(exc)}

    def get_job_progress(self, job_id: str, offset: int = 0) -> Dict[str, Any]:
        """Read fine-grained progress events via GET /jobs/{id}/progress?offset=N."""
        try:
            resp = self._session.get(f"{self.url}/jobs/{job_id}/progress?offset={int(offset)}", timeout=HEALTH_TIMEOUT)
            return resp.json()
        except Exception as exc:
            return {'status': 'error', 'error': str(exc)}

    def poll_job(self, job_id: str, interval: float = 0.5, timeout: float = 300.0,
                 on_progress=None, max_interval: float = 5.0) -> Dict[str, Any]:
        """
        Poll GET /jobs/{id} until the job reaches a terminal state or timeout elapses.
        Designed as the lightweight alternative to wait_for_job (which holds a worker slot).

        Args:
            job_id: Job identifier returned by an async skill (e.g. script_create).
            interval: Initial seconds between polls. Default 0.5s; after each poll it grows by
                1.5x up to max_interval, so a long-running job is not polled hundreds of times.
            timeout: Total wait budget in seconds. Default 5 min.
            on_progress: Optional callback (snapshot_dict) -> None invoked after each poll.
            max_interval: Upper bound (seconds) for the backoff interval. Default 5s.

        Returns the final snapshot dict (with `terminal=True` on natural completion).
        """
        deadline = time.time() + max(0.0, timeout)
        last = None
        cur = max(0.05, interval)
        while True:
            last = self.get_job(job_id)
            if isinstance(last, dict):
                if on_progress:
                    try:
                        on_progress(last)
                    except Exception:
                        pass
                if last.get('terminal') is True:
                    return last
                if last.get('errorCode') in ('NOT_FOUND', 'INTERNAL'):
                    return last
            if time.time() >= deadline:
                if isinstance(last, dict):
                    last['_pollTimeout'] = True
                return last or {'status': 'error', 'error': 'poll_job timed out'}
            time.sleep(cur)
            cur = min(max_interval, cur * 1.5)


# Global Default Client (lazy initialization)
_default_client = None

def _get_default_client():
    """Lazily initialize the default client and auto-discover an instance on first use."""
    global _default_client
    if _default_client is None:
        _default_client = UnitySkills()
    return _default_client

_auto_workflow_enabled = True  # Backward-compatible flag; single-call workflow is now handled by the Unity server.
_current_workflow_active = False  # Is an explicit WorkflowContext currently active?
_workflow_lock = threading.Lock()  # Protects _auto_workflow_enabled and _current_workflow_active

def set_auto_workflow(enabled: bool):
    """Backward-compatible toggle. Single-call auto-workflow is owned by the Unity server."""
    global _auto_workflow_enabled
    with _workflow_lock:
        _auto_workflow_enabled = enabled

def is_auto_workflow_enabled() -> bool:
    """Check if auto-workflow is enabled."""
    with _workflow_lock:
        return _auto_workflow_enabled

def connect(port: int = None, target: str = None, version: str = None) -> UnitySkills:
    """
    Create a new UnitySkills client.
    Args:
        port: Connect to specific localhost port (e.g. 8091)
        target: Connect to instance by Name or ID
        version: Connect to instance by Unity version (e.g. "6", "2022", "2022.3")
    """
    return UnitySkills(port=port, target=target, version=version)

def set_unity_version(version: str):
    """
    Set target Unity version and reconfigure the default client.

    This is the primary way for AI agents to route to a specific Unity version
    when multiple instances are running.

    Args:
        version: Unity version string, e.g. "6", "Unity 6", "2022", "2022.3"

    Example:
        import unity_skills
        unity_skills.set_unity_version("6")       # Switch to Unity 6
        unity_skills.call_skill("gameobject_create", name="Cube")  # Auto-routes
    """
    global _default_client
    _default_client = UnitySkills(version=version)

def list_instances() -> list:
    """Return list of active Unity instances from registry."""
    data = _load_registry()
    results = []
    for info in data.values():
        results.append(dict(info))
    return results

def dry_run_skill(skill_name: str, **kwargs) -> Dict[str, Any]:
    """Validate a Unity skill call without executing it."""
    return _get_default_client().dry_run_skill(skill_name, **kwargs)


def plan_skill(skill_name: str, **kwargs) -> Dict[str, Any]:
    """Preview a Unity skill call with generic/semantic planning details."""
    return _get_default_client().plan_skill(skill_name, **kwargs)


def plan_workflow(goal: str = None, target_output: str = None, max_depth: int = 3,
                  skills: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    """
    Plan a multi-step workflow.

    Preferred usage:
        plan_workflow(skills=[{"name": "gameobject_create", "params": {...}}, ...])

    Backward-compatible fallback:
        plan_workflow(goal="build player", target_output="scene")
    """
    if skills is None and isinstance(goal, list):
        skills = goal
        goal = None

    if skills is not None:
        return _get_default_client().plan_workflow(skills)

    result: Dict[str, Any] = {'status': 'plan', 'goal': goal, 'targetOutput': target_output}
    if goal:
        result['recommendations'] = find_skills(goal)
    if target_output:
        result['dependencyChain'] = get_skill_chain(target_output, max_depth=max_depth)
    result['note'] = 'Pass skills=[...] to call the server-side workflow_plan aggregator.'
    return result


def call_skill(skill_name: str, **kwargs) -> Dict[str, Any]:
    """Call a Unity skill. Single-call auto-workflow is handled by the Unity server."""
    return _get_default_client().call(skill_name, **kwargs)


def get_job_status(job_id: str) -> Dict[str, Any]:
    """Get status for an asynchronous UnitySkills job."""
    return _get_default_client().get_job_status(job_id)


def get_job_logs(job_id: str, limit: int = 100) -> Dict[str, Any]:
    """Get structured logs for an asynchronous UnitySkills job."""
    return _get_default_client().get_job_logs(job_id, limit=limit)


def wait_for_job(job_id: str, timeout: float = 60.0) -> Dict[str, Any]:
    """Wait for a UnitySkills job and include the final batch report when available.

    Polls GET /jobs/{id} (non-blocking) until the job is terminal or `timeout` elapses;
    does not call the blocking `job_wait` skill, so the Unity main thread is not frozen.
    `timeout` defaults to 60s.
    """
    return _get_default_client().wait_for_job(job_id, timeout=timeout)


def get_job(job_id: str) -> Dict[str, Any]:
    """Lightweight GET /jobs/{id} snapshot — preferred for high-frequency progress polling."""
    return _get_default_client().get_job(job_id)


def list_jobs(limit: int = 50) -> Dict[str, Any]:
    """List recent jobs via GET /jobs."""
    return _get_default_client().list_jobs(limit=limit)


def get_job_progress(job_id: str, offset: int = 0) -> Dict[str, Any]:
    """Read fine-grained progress events via GET /jobs/{id}/progress?offset=N."""
    return _get_default_client().get_job_progress(job_id, offset=offset)


def poll_job(job_id: str, interval: float = 0.5, timeout: float = 300.0, on_progress=None) -> Dict[str, Any]:
    """Block until a job reaches a terminal state, polling GET /jobs/{id} every `interval` seconds."""
    return _get_default_client().poll_job(job_id, interval=interval, timeout=timeout, on_progress=on_progress)


def diagnose(error_limit: int = 20, include_warnings: bool = True, include_recent_jobs: bool = True) -> Dict[str, Any]:
    """One-shot Editor health snapshot — call this FIRST when triaging problems."""
    return _get_default_client().call(
        'unity_diagnose',
        errorLimit=error_limit,
        includeWarnings=include_warnings,
        includeRecentJobs=include_recent_jobs,
    )


class WorkflowContext:
    """
    Workflow context manager for batching multiple operations into a single workflow task.

    Usage:
        with WorkflowContext('Create Scene', 'Build player and environment'):
            call_skill('gameobject_create', name='Player')
            call_skill('component_add', name='Player', componentType='Rigidbody')
    """
    def __init__(self, tag: str, description: str = ''):
        self.tag = tag
        self.description = description
        self._started = False
        self._task_id = None

    def _matches_status(self, status: Dict[str, Any]) -> bool:
        if not status.get('success') or not status.get('isRecording'):
            return False

        current_tag = status.get('currentTaskTag')
        current_description = status.get('currentTaskDescription') or ''
        if current_tag != self.tag:
            return False

        return current_description == (self.description or '')

    def _recover_started_task(self, failed_result: Dict[str, Any]) -> bool:
        global _current_workflow_active

        if not _is_retryable_transport_error(failed_result):
            return False
        if not wait_for_unity(timeout=10.0):
            return False

        status = _get_default_client().call('workflow_session_status')
        if not self._matches_status(status):
            return False

        self._started = True
        self._task_id = status.get('currentTaskId')
        with _workflow_lock:
            _current_workflow_active = True
        return True

    def _recover_ended_task(self, failed_result: Dict[str, Any]) -> bool:
        if not _is_retryable_transport_error(failed_result):
            return False
        if not wait_for_unity(timeout=10.0):
            return False

        client = _get_default_client()
        status = client.call('workflow_session_status')
        if status.get('success'):
            current_task_id = status.get('currentTaskId')
            if not status.get('isRecording'):
                return True
            if self._task_id and current_task_id != self._task_id:
                return True
            if self._matches_status(status):
                retry_result = client.call('workflow_task_end')
                return bool(retry_result.get('success'))

        return False

    def __enter__(self):
        global _current_workflow_active
        start_result = _get_default_client().call('workflow_task_start', tag=self.tag, description=self.description)
        if not start_result.get('success'):
            if self._recover_started_task(start_result):
                return self
            with _workflow_lock:
                _current_workflow_active = False
            raise RuntimeError(start_result.get('error', 'workflow_task_start failed'))

        with _workflow_lock:
            _current_workflow_active = True
        self._started = True
        self._task_id = start_result.get('taskId')
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        global _current_workflow_active
        try:
            if self._started:
                end_result = _get_default_client().call('workflow_task_end')
                if not end_result.get('success'):
                    recovered = self._recover_ended_task(end_result)
                    if exc_type is None and not recovered:
                        raise RuntimeError(end_result.get('error', 'workflow_task_end failed'))
        finally:
            with _workflow_lock:
                _current_workflow_active = False
            self._started = False
            self._task_id = None
        return False  # Do not suppress exceptions

def workflow_context(tag: str, description: str = '') -> WorkflowContext:
    """Convenience function to create a WorkflowContext."""
    return WorkflowContext(tag, description)

def call_skill_with_retry(skill_name: str, max_retries: int = 3, retry_delay: float = 2.0, **kwargs) -> Dict[str, Any]:
    """Call a Unity skill with single-layer retry tuned for Domain Reload scenarios.

    Retry lives in ONE layer: the underlying client call runs with `_retries=0`, and this
    function handles transient transport errors (compile-time TCP refusal / timeout) by polling
    /health until the server recovers, then re-sending once. This avoids the old nested-retry
    product (outer x inner) that could fire up to 16 requests and trip the rate limiter.

    Args:
        skill_name: Name of the Unity skill to call.
        max_retries: Maximum number of retry attempts after the initial call (default: 3, total attempts: 4).
        retry_delay: Base seconds budget per recovery wait (used as the /health poll window).
        **kwargs: Additional arguments passed to call_skill.

    Returns:
        The result from call_skill, or the last result if all retries are exhausted.
    """
    last_result = None
    # 收敛为单层重试：底层 call 不再自重试（_retries=0），Domain Reload 容错统一在此处理。
    kwargs.setdefault('_retries', 0)
    for attempt in range(1 + max_retries):
        result = call_skill(skill_name, **kwargs)

        if not _is_retryable_transport_error(result):
            return result

        last_result = result
        if attempt < max_retries:
            # 编译期 TCP 被拒/超时：轮询 /health 等服务恢复后再单次重发，避免盲目重试撞限流（100 req/s）。
            wait_for_unity(timeout=max(retry_delay, 1.0) * 3, check_interval=0.5)
    return last_result

def get_skills(category: str = None, operation: str = None, tags: str = None,
               read_only: bool = None, q: str = None) -> Dict[str, Any]:
    """Get list of available skills, optionally filtered by metadata.

    Args:
        category: Filter by SkillCategory (e.g. "GameObject", "Material").
        operation: Filter by SkillOperation (e.g. "Create", "Query").
        tags: Filter by tag (e.g. "batch", "hierarchy").
        read_only: Filter read-only skills (True/False).
        q: Text search across name, description, and tags.
    """
    try:
        client = _get_default_client()
        params = {}
        if category is not None: params["category"] = category
        if operation is not None: params["operation"] = operation
        if tags is not None: params["tags"] = tags
        if read_only is not None: params["readOnly"] = str(read_only).lower()
        if q is not None: params["q"] = q
        qs = f"?{urlencode(params)}" if params else ""
        response = client._session.get(f"{client.url}/skills{qs}", timeout=client.timeout)
        response.encoding = 'utf-8'
        return response.json()
    except Exception as e:
        return {"status": "error", "error": str(e)}

# On-disk cache layer for the large /skills payloads: short-lived CLI processes
# never benefit from the in-process dicts below, so successful summary/schema
# responses are also persisted under ~/.unity_skills/cache/ as
# {"etag", "cached_at", "payload"} JSON files, keyed per Unity instance
# (instanceId from /health, so concurrent projects never share files) + endpoint.
# Within the TTL the disk copy is served directly; past the TTL a stored ETag
# turns the refetch into a conditional GET that an unchanged payload answers
# with a bodyless 304. Any disk failure degrades silently to memory-only caching.

def _cache_dir() -> Path:
    return Path.home() / ".unity_skills" / "cache"


def _cache_file_name(instance_key: str, endpoint: str) -> str:
    # Project names may contain characters that are invalid in file names.
    safe = re.sub(r'[^A-Za-z0-9._-]+', '_', f"{instance_key}-{endpoint}")
    return f"{safe}.json"


def _disk_cache_read(instance_key: str, endpoint: str) -> Optional[Dict[str, Any]]:
    """Load a {etag, cached_at, payload} entry from disk; None on miss or any error."""
    try:
        path = _cache_dir() / _cache_file_name(instance_key, endpoint)
        with open(str(path), 'r', encoding='utf-8') as f:
            entry = json.load(f)
        if isinstance(entry, dict) and 'payload' in entry:
            return entry
    except (OSError, ValueError):
        pass
    return None


def _disk_cache_write(instance_key: str, endpoint: str, etag: Optional[str], payload: Any,
                      cached_at: Optional[float] = None):
    """Persist a cache entry; failures degrade silently to memory-only caching."""
    try:
        cache_dir = _cache_dir()
        cache_dir.mkdir(parents=True, exist_ok=True)
        entry = {
            'etag': etag,
            'cached_at': cached_at if cached_at is not None else time.time(),
            'payload': payload,
        }
        path = cache_dir / _cache_file_name(instance_key, endpoint)
        with open(str(path), 'w', encoding='utf-8') as f:
            json.dump(entry, f, ensure_ascii=False)
    except (OSError, ValueError, TypeError):
        pass


def _instance_cache_key(client: "UnitySkills") -> Optional[str]:
    """Disk-cache key identifying one Unity instance.

    Prefers instanceId from /health (stable project-name + path-hash), falling
    back to projectName+port for older servers. Returns None when /health is
    unreachable or carries neither field — callers then skip the disk layer.
    """
    health = client._get_health_info()
    if not health:
        return None
    instance_id = health.get('instanceId')
    if instance_id:
        return str(instance_id)
    project = health.get('projectName')
    if project:
        port = (client.url or '').rsplit(':', 1)[-1]
        return f"{project}_{port}"
    return None


def _fetch_with_cache(client: "UnitySkills", path: str, endpoint: str,
                      mem_cache: Dict[str, Dict[str, Any]], ttl: float,
                      validate, force_refresh: bool) -> Dict[str, Any]:
    """Shared memory -> disk -> conditional-GET pipeline for /skills payloads.

    Order: a fresh in-memory entry wins; otherwise a fresh disk entry is promoted
    to memory; otherwise the request goes out — with If-None-Match when the stale
    disk entry carries an ETag, so an unchanged payload costs a 304 instead of a
    full body. Validated 200 responses update both layers (the ETag is stored only
    when the server sent one; without it the disk entry works as plain TTL cache).
    force_refresh bypasses both cache layers and refetches unconditionally.
    """
    key = client.url or "default"
    now = time.time()
    cached = mem_cache.get(key)
    if not force_refresh and cached and (now - cached["ts"]) < ttl:
        return cached["data"]

    instance_key = _instance_cache_key(client)
    disk_entry = None
    if not force_refresh and instance_key:
        disk_entry = _disk_cache_read(instance_key, endpoint)
        if disk_entry and not validate(disk_entry.get('payload')):
            disk_entry = None  # corrupt/foreign file: ignore it and refetch below
        if disk_entry and (now - disk_entry.get('cached_at', 0)) < ttl:
            mem_cache[key] = {"ts": disk_entry['cached_at'], "data": disk_entry['payload']}
            return disk_entry['payload']

    headers = {}
    etag = disk_entry.get('etag') if disk_entry else None
    if etag:
        headers['If-None-Match'] = etag

    response = client._session.get(f"{client.url}{path}", timeout=client.timeout, headers=headers)
    response.encoding = 'utf-8'

    if response.status_code == 304 and disk_entry:
        payload = disk_entry['payload']
        mem_cache[key] = {"ts": now, "data": payload}
        if instance_key:
            _disk_cache_write(instance_key, endpoint, etag, payload, cached_at=now)
        return payload

    data = response.json()
    if validate(data):
        mem_cache[key] = {"ts": now, "data": data}
        if instance_key:
            _disk_cache_write(instance_key, endpoint, response.headers.get('ETag'), data, cached_at=now)
    return data


# Process-wide lite-summary cache: /skills?summary=1 is ~143 KB (~35K tokens) — the cheap
# awareness layer (name/desc/category/operation/riskLevel per skill). Cache a successful
# result per server URL for a short TTL so the agent doesn't re-pay 35K tokens to recall
# the toolset. Pull the full schema (get_skill_schema) for exact parameter schemas.
_skills_summary_cache: Dict[str, Dict[str, Any]] = {}
_SKILLS_SUMMARY_TTL = 300.0


def get_skills_summary(force_refresh: bool = False) -> Dict[str, Any]:
    """Get the lite awareness manifest (name/desc/category/operation/riskLevel per skill).

    The token-friendly first fetch (~35K tokens vs ~150K full) for project awareness;
    server-cached and client-cached (memory + disk + ETag, see _fetch_with_cache) per
    URL for _SKILLS_SUMMARY_TTL seconds. Pull the full schema via get_skill_schema()
    when you need exact parameter schemas to execute.
    """
    try:
        client = _get_default_client()
        return _fetch_with_cache(
            client, "/skills?summary=1", "summary",
            _skills_summary_cache, _SKILLS_SUMMARY_TTL,
            validate=lambda d: isinstance(d, dict) and d.get("summary") is True,
            force_refresh=force_refresh,
        )
    except Exception as e:
        return {"status": "error", "error": str(e)}


def search_skills(query: str, category: str = None, limit: int = 20) -> List[Dict[str, Any]]:
    """Keyword search over the lite skills summary — avoids loading the full
    summary (~143 KB / ~35K tokens) into context; only matching entries are returned.

    Data comes from get_skills_summary() (memory + disk + ETag cached), so repeated
    searches within the TTL re-read the cache instead of re-fetching the payload.

    Matching: `query` is split on whitespace; a skill matches only when EVERY term
    is a case-insensitive substring of its name, description, or category (AND).
    `category`, when given, additionally filters by exact category name
    (case-insensitive). Results are ordered by how many terms hit the name
    (more first), then by name alphabetically.

    Args:
        query: Whitespace-separated keywords. Empty/None returns [] (never the full list).
        category: Optional exact category filter, e.g. "ScriptableObject".
        limit: Maximum number of results (default 20).

    Returns:
        List of {name, category, description} dicts, at most `limit` entries.
        On summary fetch failure returns [{"status": "error", "error": "..."}]
        (same convention as get_audit_log).

    Example:
        search_skills("serialized property")
        search_skills("create", category="Material", limit=5)
    """
    if not query:
        return []
    terms = [t.lower() for t in query.split()]
    if not terms:
        return []

    summary = get_skills_summary()
    if not isinstance(summary, dict) or summary.get('status') == 'error':
        error = summary.get('error') if isinstance(summary, dict) else 'invalid summary payload'
        return [{"status": "error", "error": str(error)}]

    category_filter = category.lower() if category else None
    matches = []
    for skill in summary.get('skills') or []:
        if not isinstance(skill, dict):
            continue
        name = str(skill.get('name') or '')
        desc = str(skill.get('description') or '')
        cat = str(skill.get('category') or '')
        if category_filter and cat.lower() != category_filter:
            continue
        name_l, desc_l, cat_l = name.lower(), desc.lower(), cat.lower()
        if not all(t in name_l or t in desc_l or t in cat_l for t in terms):
            continue
        name_hits = sum(1 for t in terms if t in name_l)
        matches.append((-name_hits, name_l, {'name': name, 'category': cat, 'description': desc}))

    matches.sort(key=lambda m: (m[0], m[1]))
    results = [entry for _, _, entry in matches]
    if limit is not None:
        results = results[:max(0, limit)]
    return results


# Process-wide schema cache: /skills/schema is ~618 KB; re-fetching it per call is the
# single biggest client-side token sink. Cache a successful result per server URL for a
# short TTL and reuse it within a session.
_schema_cache: Dict[str, Dict[str, Any]] = {}
_SCHEMA_CACHE_TTL = 300.0  # seconds


def get_skill_schema(force_refresh: bool = False) -> Dict[str, Any]:
    """Get the canonical machine-readable skill schema (memory + disk cached).

    This is the preferred source for exact skill names, parameters, and metadata
    when prompt/token budget matters more than loading large SKILL.md files.

    The full schema is large (~618 KB), so a successful result is cached per server URL
    for `_SCHEMA_CACHE_TTL` seconds (plus an on-disk ETag cache shared across processes,
    see _fetch_with_cache). Pass force_refresh=True to bypass the cache (e.g. after
    adding/renaming skills and recompiling).
    """
    try:
        client = _get_default_client()
        return _fetch_with_cache(
            client, "/skills/schema", "full",
            _schema_cache, _SCHEMA_CACHE_TTL,
            validate=lambda d: isinstance(d, dict) and d.get("totalSkills") is not None,
            force_refresh=force_refresh,
        )
    except Exception as e:
        return {"status": "error", "error": str(e)}


def find_skills(intent: str, top_n: int = 10) -> Dict[str, Any]:
    """Server-side intent-based skill recommendation.

    Uses keyword scoring: name match (3pts), tag match (2pts), description match (1pt).
    Returns top-N ranked skills with relevance scores.

    Args:
        intent: Natural language description of what you want to do (e.g. "create red cube").
        top_n: Maximum number of results (default 10, max 50).
    """
    try:
        client = _get_default_client()
        params = {"intent": intent, "topN": str(top_n)}
        response = client._session.get(
            f"{client.url}/skills/recommend?{urlencode(params)}", timeout=client.timeout)
        response.encoding = 'utf-8'
        return response.json()
    except Exception as e:
        return {"status": "error", "error": str(e)}


def get_skill_chain(target_output: str, max_depth: int = 3) -> Dict[str, Any]:
    """Find skill producers and dependency chain for a specific output field via the server."""
    try:
        client = _get_default_client()
        params = {"output": target_output, "maxDepth": str(max_depth)}
        response = client._session.get(
            f"{client.url}/skills/chain?{urlencode(params)}", timeout=client.timeout)
        response.encoding = 'utf-8'
        return response.json()
    except Exception as e:
        return {"status": "error", "error": str(e)}


def health() -> bool:
    """Check if the current default Unity server is running."""
    try:
        client = _get_default_client()
        response = client._session.get(f"{client.url}/health", timeout=HEALTH_TIMEOUT)
        response.encoding = 'utf-8'
        return response.json().get("status") == "ok"
    except (requests.exceptions.RequestException, ValueError):
        return False


def is_unity_running() -> bool:
    """Alias for health()."""
    return health()


def wait_for_unity(timeout: float = 10.0, check_interval: float = 1.0) -> bool:
    """Wait for Unity REST server to become available again."""
    start_time = time.time()
    while time.time() - start_time < timeout:
        if health():
            return True
        time.sleep(check_interval)
    return False


# ============================================================
# Unity CLI integration (opt-in via the UnitySkills panel)
# ============================================================

def get_cli_config(project_root: Optional[str] = None) -> Optional[Dict[str, Any]]:
    """Read the Unity CLI binding config written by the UnitySkills panel.

    Returns the parsed dict from <project_root>/Library/UnitySkills/cli_config.json,
    or None if the file is missing/unreadable OR 'enabled' is false — None means
    "Unity CLI is OFF for this project", so callers can gate on a single check.
    project_root defaults to the current working directory.
    """
    root = project_root or os.getcwd()
    path = os.path.join(root, 'Library', 'UnitySkills', 'cli_config.json')
    try:
        with open(path, 'r', encoding='utf-8') as f:
            cfg = json.load(f)
        if not cfg.get('enabled') or not cfg.get('cliPath'):
            return None
        # projectPath in the file is a snapshot taken at bind time; if the project
        # was moved/renamed since, that stale path could point elsewhere. The
        # directory we actually found the config under is authoritative.
        cfg['projectPath'] = os.path.abspath(root)
        return cfg
    except (OSError, ValueError):
        return None


def wait_for_health(timeout: float = 600.0, check_interval: float = 3.0) -> Optional[Dict[str, Any]]:
    """Wait for a UnitySkills server after a cold start (unity CLI `open`).

    Unlike wait_for_unity(), this resets the cached default client on every
    attempt so port discovery reruns — required when the editor was launched
    fresh and may bind any port in the 8090-8100 range. First import/compile
    can take minutes; default timeout is generous. Returns the /health payload
    once reachable, or None on timeout.
    """
    global _default_client
    start_time = time.time()
    while time.time() - start_time < timeout:
        _default_client = None
        try:
            client = _get_default_client()
            resp = client._session.get(f"{client.url}/health", timeout=HEALTH_TIMEOUT)
            resp.encoding = 'utf-8'
            data = resp.json()
            if data.get('status') == 'ok':
                return data
        except (requests.exceptions.RequestException, ValueError, RuntimeError):
            pass
        time.sleep(check_interval)
    return None


def get_server_status() -> Dict[str, Any]:
    """Get detailed health information from the current Unity server."""
    try:
        client = _get_default_client()
        response = client._session.get(f"{client.url}/health", timeout=HEALTH_TIMEOUT)
        response.encoding = 'utf-8'
        return response.json()
    except requests.exceptions.ConnectionError:
        return {'status': 'offline', 'reason': 'Server not running or Unity recompiling'}
    except Exception as e:
        return {'status': 'error', 'reason': str(e)}


# ============================================================
# Permission System
# ============================================================

def _permission_get(path: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """内部辅助：向 /permission/* GET 端点发起请求并返回 JSON。"""
    client = _get_default_client()
    qs = f"?{urlencode(params)}" if params else ""
    response = client._session.get(f"{client.url}{path}{qs}", timeout=client.timeout)
    response.encoding = 'utf-8'
    return response.json()


def _permission_post(path: str, payload: Dict[str, Any]) -> Dict[str, Any]:
    """内部辅助：向 /permission/* POST 端点发送 JSON body 并返回响应 JSON。"""
    client = _get_default_client()
    json_data = json.dumps(payload, ensure_ascii=False)
    response = client._session.post(
        f"{client.url}{path}",
        data=json_data.encode('utf-8'),
        headers={'Content-Type': 'application/json; charset=utf-8'},
        timeout=client.timeout,
    )
    response.encoding = 'utf-8'
    return response.json()


def get_permission_status(token: str = None) -> Dict[str, Any]:
    """获取权限系统状态（当前模式、已授权、待批列表等）。

    返回内容含 ``mode``、``panelApprovalRequired``、``granted``、``forbidden``、
    ``pending``、``counts``。若传入 ``token``，响应会额外包含 ``focus`` 字段
    （含 ``approvedByPanel``、``skill`` 等），用于查询特定 grant 请求的状态——
    Panel 渠道下轮询审批结果时常用。

    Args:
        token: 可选，传入查询特定 grant 请求状态。
    """
    try:
        params = {'token': token} if token else None
        return _permission_get('/permission/status', params)
    except Exception as e:
        return {"status": "error", "error": str(e)}


def grant_permission(skill: str, token: str, args: Dict[str, Any]) -> Dict[str, Any]:
    """单次一步执行 grant：AI 用此把 ``MODE_RESTRICTED`` 的请求换成执行结果。

    ``args`` 必须与原 skill 调用一致（不含 ``_confirm``），服务端会用其重算
    hash 校验 token-args 绑定，防止 AI 拿一个 token 套到其它 skill 调用上。

    **响应结构（v1.9 重构后）**：成功时返回
    ``{ok: True, executed: True, skill, result: <原 skill 的 Execute 输出>}``。
    服务端在 grant 通过的同一次请求里直接执行了该 skill，**AI 不需要再调一次
    原 skill 端点** —— 直接消费 ``result`` 即可。grant 不再写入永久白名单，
    同一 skill 第二次调用仍会触发 ``MODE_RESTRICTED``，需要重新走 grant。

    Panel 渠道下若 AI 在用户点 Approve 之前调用，会返回
    ``{ok: False, reason: "GRANT_PENDING_APPROVAL"}``，应提示用户去 Unity
    面板点 Approve，再用 ``get_permission_status(token=...)`` 轮询审批结果，
    确认后再调一次 ``grant_permission`` 拿 ``result``。

    Example::

        resp = grant_permission(skill="scene_save", token=tk, args={"path": "..."})
        if resp.get("ok") and resp.get("executed"):
            return resp["result"]  # 直接拿 skill 执行结果，不需要再调 scene_save

    Args:
        skill: 待授权并执行的 skill 名。
        token: 服务端在 ``MODE_RESTRICTED`` 错误响应里发的 ``grantRequestToken``。
        args: 原 skill 调用参数（dict），不含 ``_confirm``。
    """
    try:
        return _permission_post('/permission/grant',
                                {'skill': skill, 'token': token, 'args': args})
    except Exception as e:
        return {"status": "error", "error": str(e)}


def approve_grant(token: str) -> Dict[str, Any]:
    """Panel 渠道用：面板按钮触发，仅标记本次 grant 已批准（单次有效，不写永久白名单）。

    主要给测试用；生产流程下应由 Unity 面板用户点 [Approve] 触发。
    """
    try:
        return _permission_post('/permission/approve', {'token': token})
    except Exception as e:
        return {"status": "error", "error": str(e)}


def deny_grant(token: str) -> Dict[str, Any]:
    """Panel 渠道用：拒绝 grant 请求并清除 token。"""
    try:
        return _permission_post('/permission/deny', {'token': token})
    except Exception as e:
        return {"status": "error", "error": str(e)}


def revoke_permission(skill: str = None, all: bool = False) -> Dict[str, Any]:
    """[Deprecated] 请改用 ``remove_from_allowlist``。

    撤销单个 skill 或全部白名单条目。``skill`` 与 ``all`` 二选一。
    v1.9 起 ``/permission/revoke`` 仅作为 ``/permission/allowlist/remove`` 的
    转发别名，下一个 minor 版本会移除。

    Args:
        skill: 待撤销的 skill 名，与 ``all`` 互斥。
        all: 设为 True 时撤销所有白名单条目（忽略 ``skill`` 参数）。
    """
    try:
        payload: Dict[str, Any] = {'all': True} if all else {'skill': skill}
        return _permission_post('/permission/revoke', payload)
    except Exception as e:
        return {"status": "error", "error": str(e)}


def list_allowlist() -> Dict[str, Any]:
    """GET /permission/allowlist —— 列出当前用户白名单 skill。

    返回 ``{allowlist: [...], count: N}``。白名单 skill 跳过 Approval/MODE_RESTRICTED
    门禁直接放行，可覆盖 Delete / PlayMode / Reload / RiskLevel=high 等 ModeGate 高危拦截；
    但**不绕过** ConfirmationToken 二次确认（若 RequireConfirmation 开启，仍需 _confirm 重放）。
    白名单由用户在 Unity 面板手动管理；AI 一般不应调用 add/remove。
    """
    try:
        return _permission_get('/permission/allowlist')
    except Exception as e:
        return {"status": "error", "error": str(e)}


def add_to_allowlist(skill: str) -> Dict[str, Any]:
    """POST /permission/allowlist/add —— 把 skill 加入白名单。

    注意：白名单命中后该 skill 在所有模式下绕过 Approval/MODE_RESTRICTED 门禁，
    **包括 Delete / PlayMode / Reload / RiskLevel=high 等 ModeGate 高危拦截**；但**不绕过**
    ConfirmationToken 二次确认（高危 skill 在 RequireConfirmation 开启时仍走 _confirm 握手）。
    建议仅在用户明确授权的会话场景使用
    （例如批量任务前用户同意把若干 skill 加白名单方便后续直接调）。

    Args:
        skill: 待加入白名单的 skill 名。
    """
    try:
        return _permission_post('/permission/allowlist/add', {'skill': skill})
    except Exception as e:
        return {"status": "error", "error": str(e)}


def remove_from_allowlist(skill: str = None, all: bool = False) -> Dict[str, Any]:
    """POST /permission/allowlist/remove —— 从白名单移除一项或全部。

    传 ``skill="..."`` 移除单项；传 ``all=True`` 清空全部。

    Args:
        skill: 待移除的 skill 名，与 ``all`` 互斥。
        all: 设为 True 时清空全部白名单（忽略 ``skill`` 参数）。
    """
    try:
        payload: Dict[str, Any] = {'all': True} if all else {'skill': skill}
        return _permission_post('/permission/allowlist/remove', payload)
    except Exception as e:
        return {"status": "error", "error": str(e)}


def get_audit_log(limit: int = 100) -> List[Dict[str, Any]]:
    """读取审计日志最近 N 条。

    每条是 dict（来自 jsonl），含 ``ts``、``type``、``skill``、``token`` 等字段。
    审计日志在所有模式下都会写入，可用于反查 AI 行为合规性。

    请求失败时返回单元素列表 ``[{"status": "error", "error": "..."}]``，
    便于调用方在不引入额外判空逻辑的前提下感知错误。
    """
    try:
        data = _permission_get('/permission/audit', {'limit': str(limit)})
        if isinstance(data, dict):
            return data.get('entries', [])
        return data if isinstance(data, list) else []
    except Exception as e:
        return [{"status": "error", "error": str(e)}]


def create_script(name: str, template: str = 'MonoBehaviour', wait_for_compile: bool = True) -> Dict[str, Any]:
    """Create a script and optionally wait for recompilation to settle."""
    result = call_skill('script_create', name=name, template=template)
    compilation = result.get('compilation', {}) if isinstance(result, dict) else {}
    if result.get('success') and wait_for_compile and compilation.get('isCompiling'):
        time.sleep(2)
        if wait_for_unity(timeout=10):
            feedback = call_skill('script_get_compile_feedback', scriptPath=result['path'])
            if feedback.get('success'):
                result['compilation'] = {k: v for k, v in feedback.items() if k != 'success'}
    return result


_CLI_INT_PATTERN = re.compile(r'^[+-]?\d+$')
_CLI_FLOAT_PATTERN = re.compile(r'^[+-]?(?:\d+\.\d*|\.\d+|\d+[eE][+-]?\d+|\d+\.\d*[eE][+-]?\d+|\.\d+[eE][+-]?\d+)$')


def _parse_cli_value(value: str) -> Any:
    lower_value = value.lower()
    if lower_value == 'true':
        return True
    if lower_value == 'false':
        return False
    if _CLI_INT_PATTERN.fullmatch(value):
        try:
            return int(value)
        except ValueError:
            return value
    if _CLI_FLOAT_PATTERN.fullmatch(value):
        try:
            return float(value)
        except ValueError:
            return value
    return value

def _module_helper_names() -> set:
    """Public functions/classes defined in this module.

    Introspected rather than hardcoded so a newly added helper is covered without touching
    this list. Used by main() to reject a helper name passed where a skill name is expected.
    """
    return {
        name for name, obj in globals().items()
        if callable(obj)
        and not name.startswith('_')
        and getattr(obj, '__module__', None) == __name__
    }


# ============================================================
# Main CLI Entry Point
# ============================================================
def main():
    """Command-line interface for Unity Skills."""
    import argparse

    parser = argparse.ArgumentParser(
        description='Unity Skills Python CLI',
        usage='python unity_skills.py [options] <skill_name> [param1=value1] ...'
    )
    parser.add_argument('--list', action='store_true', help='List all available skills')
    parser.add_argument('--search', type=str, default=None, metavar='QUERY',
                        help='Search skills by keyword against the cached summary, e.g. --search "gradient scriptableobject"')
    parser.add_argument('--list-instances', action='store_true', help='List active Unity instances')
    parser.add_argument('--port', type=int, default=None, help='Connect to specific port')
    parser.add_argument('--version', type=str, default=None, dest='unity_version',
                        help='Connect to Unity instance by version (e.g. "6", "2022", "2022.3")')
    parser.add_argument('skill_name', nargs='?', help='Skill name to execute')
    parser.add_argument('params', nargs='*', help='Skill parameters as key=value pairs')

    args = parser.parse_args()

    if args.port or args.unity_version:
        global _default_client
        _default_client = UnitySkills(port=args.port, version=args.unity_version)

    if args.search is not None:
        results = search_skills(args.search)
        if results and results[0].get('status') == 'error':
            print(json.dumps(results[0], ensure_ascii=False, indent=2))
            sys.exit(1)
        for entry in results:
            print(f"{entry.get('name', '')}  [{entry.get('category', '')}]  {(entry.get('description') or '')[:100]}")
        return

    if args.list:
        print(json.dumps(get_skills(), ensure_ascii=False, indent=2))
        return
    elif args.list_instances:
        print(json.dumps(list_instances(), ensure_ascii=False, indent=2))
        return

    if not args.skill_name:
        parser.print_help()
        sys.exit(1)

    # The positional argument is a skill name, so anything passed here gets POSTed to
    # /skill/<name>. A helper name (get_skill_schema, health, create_script, ...) is not in the
    # skill registry and can only come back as SKILL_NOT_FOUND — reject it locally with the
    # correct call form instead of spending a round trip on a guaranteed failure.
    if args.skill_name in _module_helper_names():
        print(json.dumps({
            "status": "error",
            "errorCode": "SKILL_NOT_FOUND",
            "error": f"'{args.skill_name}' is a Python helper in unity_skills.py, not a skill name. "
                     f"POST /skill/{args.skill_name} would always fail.",
            "callItAsAFunction": f'python -c "import unity_skills; print(unity_skills.{args.skill_name}())"',
            "findRealSkills": 'python unity_skills.py --search "<keyword>"  |  python unity_skills.py --list',
        }, ensure_ascii=False, indent=2))
        sys.exit(2)

    params = {}
    for arg in args.params:
        if '=' in arg:
            key, value = arg.split('=', 1)
            params[key] = _parse_cli_value(value)

    result = call_skill(args.skill_name, **params)

    print(json.dumps(result, ensure_ascii=False, indent=2))

if __name__ == '__main__':
    main()

# Producer:Betsy
